apiVersion: v1
kind: Template
labels:
    template: nginx-php5.6-zend2-template
metadata:
  name: nginx-php5.6-zend2-ephemeral
  annotations:
    description: "Nginx 1.10.0 with PHP 7.0 and Zend Framework 2"
    iconClass: "icon-zend"
    tags: "quickstart,php,zend"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Nginx 1.10.0
    name: ${APP_SERVICE_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying Apache
    labels:
      service: nginx-1.10.0
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: ${APP_SERVICE_NAME}
          service: nginx-1.10.0
        name: ${APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 1and1internet/ubuntu-16-nginx-1.10.0-php-5.6-zend-2:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
                port: 8080
            timeoutSeconds: 1
          name: ${APP_SERVICE_NAME}
          volumeMounts:
          - mountPath: /var/www/html
            name: nginx-data
        restartPolicy: Always
        securityContext:
          runAsUser: ${OPENSHIFT_USER}
        volumes:
        - emptyDir:
            medium: ""
          name: nginx-data
    triggers:
    - type: ConfigChange
parameters:
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  from: zend-[a-z]{5}
  generate: expression
- description: The exposed hostname that will route to the Nginx Server, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: Openshift User
  displayname: Openshift User
  name: OPENSHIFT_USER
  required: true
