#!/bin/bash

#Checking to see if the Zend Framework 2 already exists. If it does then won't install it again.

if [ ! -e "/var/www/html/index.php" ] || grep -q phpinfo index.php; then 
	echo "Zend Framework 2 doesn't appear to be installed, installing now ..."
	cd /var/www/html
	rm index*
	tar -xj --strip-components=1 -f /usr/src/tmp/zf2.tar.bz2 -C /var/www/
else
	echo "Zend Framework 2 appears to already be installed, no action taken."
	exit 0
fi

echo "Zend Framework 2 should be installed"

# chmod 755 /var/www
